---
abstract: 'A Plack Middleware for rate-limiting incoming HTTP requests.'
author:
  - 'franck cuny <franck@lumberjaph.net>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-Throttle
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  DateTime: 0
  Filter::Util::Call: 0
  HTTP::Request::Common: 0
  Moose: 0
  Plack: 0
  Scalar::Util: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/franckcuny/plack--middleware--throttle.git
version: 0.01
